name: Deploy main

# Fire on release creation
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
        SITE_ROOT: ${{ secrets.SITE_ROOT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        envs: GENERATE_SOURCEMAP,SITE_ROOT
        script: |
          source .nvm/nvm.sh
          cp /etc/nginx/sites-available/hotkeyeditor.com.maintenance /etc/nginx/sites-available/hotkeyeditor.com
          sudo /usr/sbin/nginx -s reload
          cd hotkeyeditor.com
          source .venv/bin/activate
          git pull origin main
          pip3 install -r requirements.txt
          cd src/frontend
          npm install
          rm -rf $SITE_ROOT/*
          npm run build
          sudo /bin/systemctl restart uwsgi
          cp /etc/nginx/sites-available/hotkeyeditor.com.production /etc/nginx/sites-available/hotkeyeditor.com
          sudo /usr/sbin/nginx -s reload